######################################################################
##
## Filename: user_logic.udo
## Created on: Mon Mar 03 2:35:58 PM Eastern Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
