######################################################################
##
## Filename: vmodcam_tb.udo
## Created on: Mon Feb 17 5:21:51 PM Eastern Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
